name: Deploy Code

on:
  release:
    types: [published]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
  KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
  CDA_HOST_NAME: tueicda-cda.srv.mwn.de
  CDA_USER_NAME: web-user
  CDA_TARGET_DIR: /var/www/cda/app/mmft-spheroid-trap-designer/

jobs:
  build:
    name: Validate & Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
  deploy_to_server:
    name: Upload to server
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create version file
        run: |
          echo "version = \"$(git describe --tags --always)\"" > mmft-spheroid-trap_version.txt

      - name: Set up SSH access
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${KNOWN_HOSTS}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          echo "${DEPLOY_KEY}" > ~/.ssh/my_rsync_key
          chmod 600 ~/.ssh/my_rsync_key
          echo "IdentityFile ~/.ssh/my_rsync_key" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Sync all application files (excluding version file)
        run: |
          rsync -avz \
            --exclude="mmft-spheroid-trap_version.txt" \
            --exclude=".git/" \
            --exclude="venv/" \
            --delete \
            -e "ssh -i ~/.ssh/my_rsync_key" \
            . ${CDA_USER_NAME}@${CDA_HOST_NAME}:${CDA_TARGET_DIR}

      - name: Create virtualenv & install dependencies on server
        run: |
          ssh -i ~/.ssh/my_rsync_key -o StrictHostKeyChecking=yes ${CDA_USER_NAME}@${CDA_HOST_NAME} << 'EOF'
            set -e

            APP_DIR="${CDA_TARGET_DIR}"
            VENV_DIR="\$APP_DIR/trap-designer"

            cd "\$APP_DIR"

            # 1) Virtualenv erstellen, falls noch nicht vorhanden
            if [ ! -d "\$VENV_DIR" ]; then
              python3 -m venv "\$VENV_DIR"
            fi

            # 2) Virtualenv aktivieren und Abhängigkeiten installieren
            source "\$VENV_DIR/bin/activate"
            pip install --upgrade pip
            pip install -r "\$APP_DIR/requirements.txt"
          EOF

      - name: Sync version file to trigger systemd path-unit
        run: |
          rsync -avz \
            --include="mmft-spheroid-trap_version.txt" \
            --exclude="*" \
            -e "ssh -i ~/.ssh/my_rsync_key" \
            mmft-spheroid-trap_version.txt ${CDA_USER_NAME}@${CDA_HOST_NAME}:${CDA_TARGET_DIR}
